name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Swift ${{ matrix.swift }} on Xcode ${{ matrix.xcode }}
    runs-on: ${{ matrix.runs-on }}
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer"
    strategy:
      fail-fast: false
      matrix:
        include:
          - swift: "6.0"
            xcode: "16.0"
            runs-on: macos-15
          - swift: "6.1"
            xcode: "16.3"
            runs-on: macos-15
          - swift: "6.2"
            xcode: "26.0"
            runs-on: macos-26
    timeout-minutes: 10
    steps:
      - name: Skip if commit is from sync workflow
        if: github.event.head_commit.author.name == 'GitHub Actions' && startsWith(github.event.head_commit.message, 'Update llama.cpp release to')
        run: |
          echo "Skipping CI for automated sync workflow commit"
          exit 0

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Swift Package Manager dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/org.swift.swiftpm
            .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v
